file_name: triviaset.csv
question_count: 25
hint_time1: 10
hint_time2: 20
skip_time: 30
question_delay: 5
question_bonusvalue: 3
mode: single
music_mode: false
order: random
category_distribution: random
length: finite
admins: admin
output: true